# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlarumApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlarumApp
  pod 'OHMySQL'
  pod 'SwiftyGif'

  target 'FlarumAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlarumAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
